[[redirects]]
from = "/get-started.html"
to = "/get-started.html"
status = 200

from = "/index.html"
to = "/index.html"
status = 200

from = "/projects.html"
to = "/projects.html"
status = 200

from = "/resources.html"
to = "/resources.html"
status = 200